### ISSUE TITLE
Tag page items disappears quickly after loading the page.

### ISSUE THREAD

**Issue by Amiru2007** [Bergbok/Spicetify-Creations#1]
### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1039.g8ddb5918
- Spicetify version: 2.34.1

- A intel core i5 machine with a 4Gb RAM
```

### 📝 Description

I appreciate the concept of having tags for spicetify. However, when I click on the tags custom app icon from the sidebar, the tags page loads, and disappears repeatedly without any error messages. Despite this issue, I am still able to add tags to my playlists. I have tried removing some custom apps and the theme I used, but none of them have resolved the problem.

### 📸 Screenshots

https://github.com/Bergbok/Spicetify-Creations/assets/79262786/6e9c58ec-7719-4342-af58-4880b89f58c6

**Comment by Bergbok** [comment]
Hmm, pretty strange. I'll look into it.

**Comment by Bergbok** [comment]
Just checking:
- Did you rename the extracted folder in AppData\Roaming\spicetify\CustomApps to playlist-tags?

It's important to rename it to exactly that.

**Comment by Bergbok** [comment]
![GIF 17-03-2024 20-44-55](https://github.com/Bergbok/Spicetify-Creations/assets/66174189/31ac20dd-0b1b-4ee2-ae8c-5cb82c5ab66f)

I recreated the behavior by renaming my folder to be incorrect.

To solve your issue, run: 
- spicetify config-dir
  - Navigate to CustomApps and rename the folder you saved it in to be playlist-tags
- spicetify config custom_apps whatEverYouCalledIt-  (with the minus at the end)
- spicetify config custom_apps playlist-tags
- spicetify apply

If this doesn't fix it for you please open another issue!

**Comment by Amiru2007** [comment]
Thanks, I renamed folders of other custom apps with my preferred names but didn't come with this issue, anyway thank you for the guide.
