### ISSUE TITLE
[Playlist Tags] Tags not displaying on playlist page

### ISSUE THREAD

**Issue by ianrispin** [Bergbok/Spicetify-Creations#10]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364
- Spicetify version: 2.38.4
- MacOS 14.5
```

### 📝 Description

Tags do not display on the playlist page. I can still see the custom app page (with the tags search), but cannot see them on playlists (and therefore can't add/remove tags).

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/1db819f8-aeb1-4e6a-a1f6-90e06c40caac)

**Comment by Bergbok** [comment]
Thanks a lot for letting me know!

I tend to use slightly outdated versions of Spotify so would've taken me a long time to notice.
