### ISSUE TITLE
Problem with uninstallation.

### ISSUE THREAD

**Issue by Venturi-exe** [Bergbok/Spicetify-Creations#12]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version : Spotify for Windows (64 bit) 1.2.48.405.gf2c48e6f
- Spicetify version : Spicetify v2.38.4 
Theme: Lucid / dark
Extensions: adblock.js, waveform.js, index.js, beautiful-lyrics.mjs, star-ratings.js, SleepTimer.js, utilities.js, djinfo.js, volume-plus.js, group-session.js, theme.js
Custom apps: history-in-sidebar, marketplace, stats, visualizer
```

### 📝 Description

Hello,
I don't know why History in Sidebar whenever i clicked on it made spicetify crash so i tried to uninstall it (in order to reinstall it properly) but now i just have a blank square that does nothing.
So my question is how do i remove this ? (Screenshot)

### 📸 Screenshots

![Screenshot 2024-10-15 201322](https://github.com/user-attachments/assets/15eef80a-cab4-4ffb-8b95-5c0c94d5377d)

**Comment by Bergbok** [comment]
Sorry to hear! Not sure what could be causing the crashes...

Seems like you just deleted the files without running: `spicetify config custom_apps history-in-sidebar-`

Let me know if that fixes it for you :)

**Comment by Venturi-exe** [comment]
Indeed it seems that i forgot to run the command when i tried to fix it.
It worked thanks you !
