### ISSUE TITLE
Icon Showing up in title bar instead of sidebar

### ISSUE THREAD

**Issue by Mysticc28** [Bergbok/Spicetify-Creations#13]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
-Spotify for Windows (64 bit)
1.2.49.439.gfae492c7
-Spicetify v2.38.4
xpui_2024-10-21_1729514985745_fae492c
cef_129.0.11+g57354b8+chromium-129.0.6668.90
Runtime: Chrome
Build System: Bazel
```

### 📝 Description

The Recently played icon (History) shows up in the titlebar instead of the sidebar. I have reinstalled both Spicetify and Spotify to check the issue but it doesn't seem to work. Also, the theme being used is Lucid by Sanoojes with dynamic colour on.  Also, is there any way the marketplace icon can also be added in the sidebar along with the history icon? Thanks in advance.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/9a3f3aac-255f-4dd5-804b-ffddbad0e178)

**Comment by Bergbok** [comment]
Hey, this is expected behavior. The sidebar buttons were moved to the title bar by a Spotify update.

I still use version 1.2.45.454, which I believe is the last version which supports placing the buttons on the left instead of the top.

You could try the [LibX reborn extension](https://github.com/sanoojes/spicetify-extensions?tab=readme-ov-file#libx-reborn) or use an older version of Spotify, if you're on Windows you can find them [here](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=803394557).

**Comment by Mysticc28** [comment]
Hey thanks, it works. Just had to enable the navbar option as control. Thanks a lot.

**Comment by Bergbok** [comment]
Sorry, forgot to mention you need to enable it yourself.  
Click on your profile picture, then Experimental Features, search for "Show global nav bar" and change the value to "control".

Oh, strange. What other things do you have installed? What's dynamic sidebar?  
I just tried it out for the first time a while ago on a fresh install and it was working.

**Comment by Bergbok** [comment]
> Hey thanks, it works. Just had to enable the navbar option as control. Thanks a lot.

Glad to hear :)

**Comment by Mysticc28** [comment]
> Sorry, forgot to mention you need to enable it yourself. Click on your profile picture, then Experimental Features, search for "Show global nav bar" and change the value to "control".
> 
> Oh, strange. What other things do you have installed? What's dynamic sidebar? I just tried it out for the first time a while ago on a fresh install and it was working.

I have a ton of extesnions and snippets installed however, I'll send a note of what Im running. 
[Lucid settings.txt](https://github.com/user-attachments/files/17662012/Lucid.settings.txt)
[marketplace.txt](https://github.com/user-attachments/files/17662015/marketplace.txt)

**Comment by Bergbok** [comment]
Cool thanks for sharing.  
Tested it - just remove the dynamic left sidebar snippet when you want to use LibX reborn.

**Comment by Mysticc28** [comment]
Hey just had another small request. Is there anyway I could remove these 2 buttons through a custom CSS snippet? I was successful through inspect element but couldn't through CSS. 
![image](https://github.com/user-attachments/assets/86dca8fb-a664-4248-bdde-27257a526e44)
![image](https://github.com/user-attachments/assets/182f56df-8a20-4891-a3bf-a21584dc7484)

**Comment by Bergbok** [comment]
You could try:
```css
button[aria-label="Go back"],
button[aria-label="Go forward"] {
  display: none !important;
}
```

Pretty sure it'll only work if your app is set to English tho.

**Comment by Mysticc28** [comment]
Thank you so much

**Comment by Bergbok** [comment]
No problem, you could also try:

```css
div.link-subtle.main-globalNav-historyButtons {
  display: none !important;
}
```

Should work on other languages.

![idk](https://cdn.7tv.app/emote/01G3C7CTS8000DSQYHZEZBYRH9/2x.webp)

**Comment by Mysticc28** [comment]
Thanks a lot, I really appreciate the help for my requests

**Comment by Mysticc28** [comment]
Hey there, I'm sorry to bother you. I needed some help with an extension and I would really appreciate it if you could assist me with this. 

I don't know how to implement the Page feature in the Extension. I really want to transfer the Custom App to an Extension, because its easier to install. I tried the Spicetify.Panel, but it doesn't exist anymore. Is there any way you can make an example extension and then show the files? Thanks!
