### ISSUE TITLE
Unable to add/create tags

### ISSUE THREAD

**Issue by ianrispin** [Bergbok/Spicetify-Creations#2]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.24.756.g7a7fc7f0
- Spicetify version: 2.31.3
- MacOS v14.2.1
- Spicetify theme: Comfy
```

### 📝 Description

I am unable to add tags to my playlists. The edit tags button does not appear on playlist pages. The second image is a series of errors that show up in the console when I open a playlist page

### 📸 Screenshots

![image](https://github.com/Bergbok/Spicetify-Creations/assets/50210259/207bdb24-c942-453a-8528-80329bcb63fe)
![image](https://github.com/Bergbok/Spicetify-Creations/assets/50210259/187b69c9-a6b6-4ed0-a881-1a2bc5db5496)

**Comment by Bergbok** [comment]
Would you mind running Spicetify.React.version in the browser console and letting me know what the result is?

The method I'm using to render tags on playlist pages requires V18 >. 
If it's less than that, you could try updating Spicetify by running:
- `spicetify upgrade`
- `spicetify apply`

**Comment by ianrispin** [comment]
I updated spicetify to 2.34.1, but Spicetify.React.version still returns 17.0.2

**Comment by Bergbok** [comment]
Apparently the version of React that Spicetify uses is based on your Spotfiy installation.

I see you're still on Spotify V1.2.24, it uses React V18 since V1.2.26, so updating Spotify should fix your issue.

**Comment by Bergbok** [comment]
Also, I just released a lil update that fixes the tag section clipping into the play button when using Comfy.

Doesn't fix it if the page that loads when starting Spotify is a playlist but does on any future page visits.

**Comment by ianrispin** [comment]
Thanks, I see it now!
