### ISSUE TITLE
history on sidebar crashes the page

### ISSUE THREAD

**Issue by averagearchenjoyer** [Bergbok/Spicetify-Creations#3]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.31.1205-2
- Spicetify version: latest
```

### 📝 Description

installed history in sidebar app as described in manual, applied config and restarted spotify. when opening history-in-sidebar i'm getting error "Something went wrong Try loading the page" everywhere, reloading page helps but history app doesn't work

### 📸 Screenshots

![image](https://github.com/Bergbok/Spicetify-Creations/assets/117821512/6e32fc85-8629-41ed-9373-7a9b45cd4431)

**Comment by Bergbok** [comment]
Hey - I'm not too sure what could be causing this.
The app itself is super simple so I doubt anything is wrong with the code - thinking it must be setup incorrectly.

Would you mind letting me know which error you're getting from the browser console?
To view, run `spicetify enable-devtools` and press <kbd>Ctrl + Shift + I</kbd> within Spotify

Also, make sure you downloaded it from [here](https://github.com/Bergbok/Spicetify-Creations/archive/refs/heads/dist/history-in-sidebar.zip) and that your folder structure looks like this:
![Untitled-3](https://github.com/Bergbok/Spicetify-Creations/assets/66174189/4f1a9923-82a6-46e9-8199-e800611856d7)

You could try updating Spotify as well - I see you're still on 1.2.31, kinda doubt it will fix your problem though.

**Comment by Bergbok** [comment]
Closing due to a lack of response. 

I hope you could figure it out, if you still need help feel free to open another issue. <3
