### ISSUE TITLE
getting index.js missing for both custom apps

### ISSUE THREAD

**Issue by elsoba** [Bergbok/Spicetify-Creations#7]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version:latest
```

### 📝 Description

index.js not included for custom apps
 
Transferring custom apps:
error Custom app "history-in-sidebar" does not have index.js
error Custom app "playlist-tags" does not have index.js

### 📸 Screenshots

![Captura de tela 2024-06-13 022040](https://github.com/Bergbok/Spicetify-Creations/assets/84707822/7486c125-4af7-4155-b5c5-a3d8db187587)
![Captura de tela 2024-06-13 022109](https://github.com/Bergbok/Spicetify-Creations/assets/84707822/91c19493-4d41-4986-b561-b17133170dbb)

**Comment by Bergbok** [comment]
You downloaded the source code, not the built apps.

Use these links or the ones in the READMEs "Installation" sections to download them.

- [Playlist Tags](https://github.com/Bergbok/Spicetify-Creations/archive/refs/heads/dist/playlist-tags.zip)
- [History in Sidebar](https://github.com/Bergbok/Spicetify-Creations/archive/refs/heads/dist/history-in-sidebar.zip)

Or navigate to their respective dist [branch](https://github.com/Bergbok/Spicetify-Creations/branches) and download them from there.

**Comment by tired9494** [comment]
ahh I did not realise "Download it from [here](https://github.com/Bergbok/Spicetify-Creations/archive/refs/heads/dist/history-in-sidebar.zip)" was referring to the app, I thought it was referring to Spicetify. Might want to reword that step

**Comment by Bergbok** [comment]
@tired9494 Fair enough, I can see how it could be confusing. I'll make it more clear sometime.
Thanks for the feedback!
