### ISSUE TITLE
The history screen never shows anything

### ISSUE THREAD

**Issue by qixing-jk** [Bergbok/Spicetify-Creations#9]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Windows (64-bit) Edition 1.2.45.454.gc16ec9f6
- Spicetify version: 2.37.7
```

### 📝 Description

Click on the History button in the sidebar, the corresponding screen is empty

**Comment by Bergbok** [comment]
Yeah sorry about that, I've known about this for a while and probably should've updated the README or something.

Spotify moved the "recently played" section from a dedicated page to the right sidebar, so I need to update it.

I just need to figure out how to open the right sidebar with a command first.
